networks:
  monitoring_network:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    container_name: prom_container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - monitoring_network
  grafana:
    image: grafana/grafana
    container_name: grafana_cont
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - monitoring_network
  node-exporter:
    image: prom/node-exporter
    container_name: node_export__container
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    networks:
      - monitoring_network
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_export__container
    ports:
      - 9115:9115
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - --config.file=/config/blackbox.yml
    networks:
      - monitoring_network
